hotfix

diff --git a/.gitlab-ci-terraform.yml b/.gitlab-ci-terraform.yml
--- a/.gitlab-ci-terraform.yml
+++ b/.gitlab-ci-terraform.yml
@@ -21,14 +21,18 @@
         -backend-config="lock_method=POST" \
         -backend-config="unlock_method=DELETE" \
         -backend-config="retry_wait_min=5"
+
+    - |
+      echo "Attempting to delete existing Minikube profile '$MINIKUBE_PROFILE'..."
+      minikube delete -p $MINIKUBE_PROFILE || true # The '|| true' ensures the script doesn't fail if the profile doesn't exist
+      echo "Minikube profile deletion complete (or profile did not exist)."
+
     - |
       if ! minikube status -p $MINIKUBE_PROFILE | grep -q "Running"; then
-        minikube start --memory=6656 --cpus=4 --driver=docker -p $MINIKUBE_PROFILE --wait=all --apiserver-ips=127.0.0.1 --apiserver-name=localhost
+        minikube start --memory=6656 --cpus=4 --driver=docker -p $MINIKUBE_PROFILE --wait=all -v=7
       else
         echo "Minikube profile $MINIKUBE_PROFILE is already running"
       fi
-    - minikube update-context -p $MINIKUBE_PROFILE
-
     - minikube update-context -p $MINIKUBE_PROFILE
 
     - |
